[0m15:50:43.586147 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC6DB2E0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC714D3AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC7260FDD0>]}


============================== 15:50:43.623589 | dcfc4e8d-ff26-4874-90e9-97959a353f04 ==============================
[0m15:50:43.623589 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:50:43.623589 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\vincent.cotineau\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init IDL-PBI-Sustain', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:50:43.877398 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/vincent.cotineau/.dbt')}
[0m15:50:43.877398 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:51:08.578418 [debug] [MainThread]: Starter project path: C:\Users\vincent.cotineau\Documents\Repos\IDL-PBI-Sustain\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m15:51:08.615538 [info ] [MainThread]: 
Your new dbt project "IDL_PBI_Sustain" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:51:08.627957 [info ] [MainThread]: Setting up your profile.
[0m15:56:40.765233 [info ] [MainThread]: Profile IDL_PBI_Sustain written to C:\Users\vincent.cotineau\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:56:40.770907 [debug] [MainThread]: Command `dbt init` succeeded at 15:56:40.770907 after 357.40 seconds
[0m15:56:40.770907 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC6E9413D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC7339BF80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC6FCCFD40>]}
[0m15:56:40.773368 [debug] [MainThread]: Flushing usage events
[0m15:56:41.070631 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:21:01.352903 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C3783825D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C3783806E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C3783830B0>]}


============================== 12:21:01.396848 | 6389ebed-9a2f-4bc2-a9a3-b20b4070f994 ==============================
[0m12:21:01.396848 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:21:01.396848 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\vincent.cotineau\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run --select dim_answer', 'send_anonymous_usage_stats': 'True'}
[0m12:21:01.396848 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\vincent.cotineau\Documents\Repos\IDL-PBI-Sustain\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:21:01.404970 [debug] [MainThread]: Command `dbt run` failed at 12:21:01.404970 after 0.32 seconds
[0m12:21:01.404970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C3784C4050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C377FCA840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C3783830B0>]}
[0m12:21:01.404970 [debug] [MainThread]: Flushing usage events
[0m12:21:01.579123 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:33:38.732873 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191C851F4A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191C851FAA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191C851D310>]}


============================== 17:33:38.750407 | 1d720f65-761f-42bf-baca-8e9554cb8188 ==============================
[0m17:33:38.750407 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:33:38.750407 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\vincent.cotineau\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run --select fact_answers+', 'send_anonymous_usage_stats': 'True'}
[0m17:33:38.750407 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\vincent.cotineau\Documents\Repos\IDL-PBI-Sustain\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:33:38.750407 [debug] [MainThread]: Command `dbt run` failed at 17:33:38.750407 after 0.26 seconds
[0m17:33:38.750407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191C79DFA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191C8B7B530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191C8BC7FE0>]}
[0m17:33:38.750407 [debug] [MainThread]: Flushing usage events
[0m17:33:39.037793 [debug] [MainThread]: An error was encountered while trying to flush usage events
